[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "grain"
version = "0.2.5"
description = "Grain: A library for loading and transforming data for neural network training."
keywords = []
authors = [
    {name = "Grain team", email = "grain-dev@google.com"},
]
dependencies = [
    'absl-py',
    'array-record',
    'cloudpickle',
    'dm-tree',
    'etils[epath,epy]',
    'more-itertools>=9.1.0',
    'numpy',
    'protobuf>=4.25.2',
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
]

[project.optional-dependencies]
testing = [
    'attrs',
    'dill',
    'jax',
    'jaxlib',
    'jaxtyping',
    'tensorflow',
    'tensorflow-datasets',
]

[project.urls]
homepage = "https://github.com/google/grain"

[tool.setuptools.packages.find]
include = ["grain*"]

[tool.setuptools.package-data]
"*" = ["*.so"]
